### PR TITLE
fix #106

### LINKED ISSUE #106: Something in IRTools.jl is failing on Julia nightly
We get consistent failures on GitHub CI with Julia nigthly in our code that uses `Zygote`, which looks like some problem in `IRTools`. The error happens in three separate completely unrelated branches with different changes, so we assume our changes did not cause the issue:

https://github.com/biaslab/ReactiveMP.jl/actions/runs/4244267646/jobs/7378178164
https://github.com/biaslab/ReactiveMP.jl/actions/runs/4243540900/jobs/7376449987
https://github.com/biaslab/ReactiveMP.jl/actions/runs/4243889962/jobs/7377272496

The start of the error looks like:

```
Test threw exception
  Expression: ≈(prod(test[:method], n1, n2), n_analytical, atol = test[:tol])
  MethodError: no method matching length(::Nothing)
  
  Closest candidates are:
    length(::Union{Base.KeySet, Base.ValueIterator})
     @ Base abstractdict.jl:58
    length(::Union{SparseArrays.FixedSparseVector{Tv, Ti}, SparseArrays.SparseVector{Tv, Ti}} where {Tv, Ti})
     @ SparseArrays /opt/hostedtoolcache/julia/nightly/x64/share/julia/stdlib/v1.10/SparseArrays/src/sparsevector.jl:95
    length(::Union{LinearAlgebra.Adjoint{T, <:Union{StaticArraysCore.StaticArray{Tuple{var"#s2"}, T, 1} where var"#s2", StaticArraysCore.StaticArray{Tuple{var"#s3", var"#s4"}, T, 2} where {var"#s3", var"#s4"}}}, LinearAlgebra.Diagonal{T, <:StaticArraysCore.StaticArray{Tuple{var"#s14"}, T, 1} where var"#s14"}, LinearAlgebra.Hermitian{T, <:StaticArraysCore.StaticArray{Tuple{var"#s11", var"#s12"}, T, 2} where {var"#s11", var"#s12"}}, LinearAlgebra.LowerTriangular{T, <:StaticArraysCore.StaticArray{Tuple{var"#s19", var"#s20"}, T, 2} where {var"#s19", var"#s20"}}, LinearAlgebra.Symmetric{T, <:StaticArraysCore.StaticArray{Tuple{var"#s8", var"#s9"}, T, 2} where {var"#s8", var"#s9"}}, LinearAlgebra.Transpose{T, <:Union{StaticArraysCore.StaticArray{Tuple{var"#s2"}, T, 1} where var"#s2", StaticArraysCore.StaticArray{Tuple{var"#s3", var"#s4"}, T, 2} where {var"#s3", var"#s4"}}}, LinearAlgebra.UnitLowerTriangular{T, <:StaticArraysCore.StaticArray{Tuple{var"#s25", var"#s26"}, T, 2} where {var"#s25", var"#s26"}}, LinearAlgebra.UnitUpperTriangular{T, <:StaticArraysCore.StaticArray{Tuple{var"#s22", var"#s23"}, T, 2} where {var"#s22", var"#s23"}}, LinearAlgebra.UpperTriangular{T, <:StaticArraysCore.StaticArray{Tuple{var"#s16", var"#s17"}, T, 2} where {var"#s16", var"#s17"}}, StaticArraysCore.StaticArray{Tuple{var"#s26"}, T, 1} where var"#s26", StaticArraysCore.StaticArray{Tuple{var"#s1", var"#s4"}, T, 2} where {var"#s1", var"#s4"}, StaticArraysCore.StaticArray{<:Tuple, T}} where T)
     @ StaticArrays ~/.julia/packages/StaticArrays/pTgFe/src/abstractarray.jl:1
    ...
  
  Stacktrace:
    [1] meta(T::Any; types::Any, world::Any)
      @ IRTools.Inner ~/.julia/packages/IRTools/LbzBn/src/reflection/reflection.jl:50
    [2] meta
      @ ~/.julia/packages/IRTools/LbzBn/src/reflection/reflection.jl:43 [inlined]
    [3] has_chain_rrule(T::Type)
      @ Zygote ~/.julia/packages/Zygote/g2w9o/src/compiler/chainrules.jl:20
    [4] #s78#1107
      @ ~/.julia/packages/Zygote/g2w9o/src/compiler/interface2.jl:20 [inlined]
    [5] var"#s78#1107"(::Any, ctx::Any, f::Any, args::Any)
      @ Zygote ./none:0
    [6] (::Core.GeneratedFunctionStub)(::UInt64, ::LineNumberNode, ::Any, ::Vararg{Any})
      @ Core ./boot.jl:600
    [7] pullback(f::Function, cx::Zygote.Context{false}, args::Float64)
      @ Zygote ~/.julia/packages/Zygote/g2w9o/src/compiler/interface.jl:44
    [8] pullback
      @ ~/.julia/packages/Zygote/g2w9o/src/compiler/interface.jl:42 [inlined]
    [9] gradient(f::Function, args::Float64)
      @ Zygote ~/.julia/packages/Zygote/g2w9o/src/compiler/interface.jl:96
   [10] compute_derivative(#unused#::ZygoteGrad, f::ReactiveMP.var"#138#139"{NormalMeanVariance{Float64}}, value::Float64)
      @ ReactiveMP ~/work/ReactiveMP.jl/ReactiveMP.jl/src/ReactiveMP.jl:198
```

Zygote and IRTools versions are:

```
[e88e6eb3] Zygote v0.6.55
[7869d1d1] IRTools v0.4.8
```

Tests are failing only on Julia nightly (1.10) and are passing on 1.6, 1.7, and 1.8

### PR DESCRIPTION
**Pull request by aviatesk**
On the nightly `Base._methods_by_ftype` may return `nothing` in cases when it previously returned `false` instead.

### PR Checklist

- [ ] Tests are added
- [x] Documentation, if applicable

### CODE REVIEW

**Comment by bvdmitri** [comment]
@aviatesk But how did it work before exactly? 
If it returned `false` it would still throw an error, because `length(false) === 1`.

**Comment by ToucheSir** [comment]
Thanks! Are you able to come up with a test for this path? Regardless of whether `_methods_by_ftype` returns `false` or `nothing`, we should be testing for both cases.

File: test/reflection.jl [hunk 1]
```diff
@@ -7,6 +7,11 @@ using IRTools: Meta, meta
 
 @test meta(Tuple{typeof(f),Int}) isa Meta
 
+function g end
```
Comment (ToucheSir) [inline test/reflection.jl:10]:
```suggestion
# https://github.com/FluxML/IRTools.jl/issues/106
function g end
```

**Review by ToucheSir — APPROVED** [review]

**Comment by ToucheSir** [comment]
Thanks @aviatesk !
